version: '3'
services:
  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - 5002:5000
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
  worker:
    image: redash/redash:latest
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 1
      REDASH_COOKIE_SECRET: veryverysecret
    ports:
      - "5001:5000"
  redis:
    image: redis:3.0-alpine
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 54320:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  postgresql-data:
