FROM postgres:12.12-alpine

ENV TEST_DB test
ENV TEST_USER test

RUN apk add --update --no-cache git unzip

RUN wget -O - https://github.com/devrimgunduz/pagila/archive/refs/tags/pagila-v3.0.0.tar.gz | tar -zxvf - && \
    mkdir /docker-entrypoint-initdb.d/dump && \
    mv ./pagila-pagila-v3.0.0/pagila-schema.sql /docker-entrypoint-initdb.d/dump/pagila-schema.sql && \
    mv ./pagila-pagila-v3.0.0/pagila-data.sql /docker-entrypoint-initdb.d/dump/pagila-data.sql

COPY ./db/init-db.sh /docker-entrypoint-initdb.d/init-user-db.sh

EXPOSE 5432
CMD ["postgres"]
